
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  <<: *default
  database: catalinadelacuesta_development

test:
  <<: *default
  database: catalinadelacuesta_test

production:
  <<: *default
  database: catalinadelacuesta_production
  username: catalinadelacuesta
  password: <%= ENV['CATALINADELACUESTA_DATABASE_PASSWORD'] %>
